### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by choppin1212** [darkarp/chrome-password-hacking#10]
getting this error, when i click exe generated.

Traceback (most recent call last):
  File "server.py", line 99, in <module>
  File "server.py", line 42, in getpass
sqlite3.OperationalError: unable to open database file

**Comment by darkarp** [comment]
will check it out

**Comment by darkarp** [comment]
Do you still get the error?
If so, could you please do a couple things for me:
Download the latest source code.
Edit the python file and add a # on the start of line 128, so that it reads:
`#os.remove('server.py')`

Then save. Now move the whole folder into C:\ and run it to generate the .exe. 
Run the .exe and if the same error happens, please upload the server.py file generated as well.
