### ISSUE TITLE
create_server.py stuck on *** searching for required modules ***

### ISSUE THREAD

**Issue by RifleFish** [darkarp/chrome-password-hacking#5]
Hi, I've got an issue like the title of this thread.
It comes up after the script builds the "build, bdist.win32, winexe, collect-2.7, bundle-2.7, temp and dist" folders. I'm using Python 2.7 and py2exe 32-bit like instructed. I chose the option to email the fetched passwords via Gmail, and send them to a different email than the mail I gave up to login on Gmail.

What's going wrong here?

(Quick edit: I've left the script running like this for quite a while, so I really think it's stuck rather than actually searching for modules...)

Screenshot:
![issue](https://user-images.githubusercontent.com/45256976/51944208-bf143400-241b-11e9-974b-5cac6580d69c.png)

**Comment by darkarp** [comment]
Hi!
Please try running the script again but in powershell this time and see if the results are different.
I will try to reproduce your error meanwhile.

**Comment by darkarp** [comment]
Huh I see what the problem might be but I can't reproduce it. Could you do something for me? 
1. on line 125 of create_server.py add a # symbol to the start, so it becomes like this: `#os.remove('server.py')`

2. Run it again but this time write down all of the stuff you write on each question it asks (you can write random stuff). 

Then just post here what you wrote on each part, as well as the error AND, if possible, the lines of code of the new server.py that should be in the directory after the second step. (you can upload it to pastebin)

This is just so I can understand what's happening on your machine because I'm not getting the same error.

**Comment by darkarp** [comment]
Also, before you perform these tasks, make sure you download the project again, so we can be sure we're both testing with the same version :)

**Comment by darkarp** [comment]
Issue will be closed and marked as complete due to lack of response. If the issue persists, please create another thread.
