### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by GR8Zen** [darkarp/chrome-password-hacking#7]
When I try it out on my PC, it works fine.
But when I send it to the victim. He gets the Fake Error. And I get an email, but the password and User area  
 is blank.

**Comment by darkarp** [comment]
Hmm, that is certainly weird. Sometimes user/password or urls won't show because only part of it was saved. But if the user and pass was saved for a website, it should appear! Could you try on a different computer from yours after making sure you save a user/password, for example creating a gmail account and saving the password?

**Comment by GR8Zen** [comment]
Yeah, it is ok, most of the passwords show now, but some of them are still blank.

**Comment by darkarp** [comment]
Blank passwords usually means that the person has saved the website with a username but no password.

**Comment by darkarp** [comment]
Sometimes it happens

**Comment by darkarp** [comment]
Sometimes it happens but you shouldn't be losing any passwords, all the passwords that exist saved should appear.
